use super::{ConfigFile, ConfigItem, ConfigStatus};
use crate::ob::utils;
use anyhow::Result;

pub struct OceanBaseConfig {
    path: String,
    configs: Vec<ConfigItem>,
}

impl OceanBaseConfig {
    pub fn new() -> Self {
        Self {
            path: "/etc/security/limits.d/99-oceanbase.conf".to_string(),
            configs: vec![
                ConfigItem::new("root soft nofile".to_string(), "655360".to_string()),
                ConfigItem::new("root hard nofile".to_string(), "655360".to_string()),
                ConfigItem::new("root soft nproc".to_string(), "655360".to_string()),
                ConfigItem::new("root hard nproc".to_string(), "655360".to_string()),
                ConfigItem::new("root soft core".to_string(), "unlimited".to_string()),
                ConfigItem::new("root hard core".to_string(), "unlimited".to_string()),
                ConfigItem::new("root soft stack".to_string(), "unlimited".to_string()),
                ConfigItem::new("root hard stack".to_string(), "unlimited".to_string()),
            ],
        }
    }
}

impl Default for OceanBaseConfig {
    fn default() -> Self {
        Self::new()
    }
}

impl ConfigFile for OceanBaseConfig {
    fn path(&self) -> &str {
        &self.path
    }

    fn expected_configs(&self) -> Vec<ConfigItem> {
        self.configs.clone()
    }

    fn parse_existing(&mut self) -> Result<()> {
        let content = utils::read_file_safe(&self.path);

        for config in &mut self.configs {
            let mut found = false;
            for line in content.lines() {
                let line = line.trim();
                if line.is_empty() || line.starts_with('#') {
                    continue;
                }

                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 4 {
                    let key = format!("{} {} {}", parts[0], parts[1], parts[2]);
                    if key == config.key {
                        found = true;
                        let value = parts[3];
                        config.current_value = Some(value.to_string());
                        if value == config.value {
                            config.status = ConfigStatus::Exists;
                        } else {
                            config.status = ConfigStatus::Conflict;
                        }
                        break;
                    }
                }
            }

            if !found {
                config.status = ConfigStatus::Missing;
            }
        }

        Ok(())
    }

    fn generate_content(&self) -> String {
        let mut lines = vec![];

        lines.push("# OceanBase resource limits configuration".to_string());
        lines.push("# Generated by yo-ob prepare".to_string());
        lines.push("".to_string());

        for config in &self.configs {
            lines.push(format!("{} {}", config.key, config.value));
        }

        lines.join("\n") + "\n"
    }

    fn check(&mut self) -> Result<Vec<ConfigItem>> {
        self.parse_existing()?;
        Ok(self.configs.clone())
    }

    fn apply(&mut self, _force: bool) -> Result<()> {
        let content = self.generate_content();
        utils::write_file(&self.path, &content)?;
        Ok(())
    }
}
