use super::{ConfigFile, ConfigItem, ConfigStatus};
use crate::ob::utils;
use anyhow::Result;

pub struct SysctlConfig {
    path: String,
    configs: Vec<ConfigItem>,
}

impl SysctlConfig {
    pub fn new() -> Self {
        Self {
            path: "/etc/sysctl.d/99-oceanbase.conf".to_string(),
            configs: vec![
                ConfigItem::new("fs.aio-max-nr".to_string(), "1048576".to_string()),
                ConfigItem::new("vm.max_map_count".to_string(), "655360".to_string()),
            ],
        }
    }
}

impl Default for SysctlConfig {
    fn default() -> Self {
        Self::new()
    }
}

impl ConfigFile for SysctlConfig {
    fn path(&self) -> &str {
        &self.path
    }

    fn expected_configs(&self) -> Vec<ConfigItem> {
        self.configs.clone()
    }

    fn parse_existing(&mut self) -> Result<()> {
        let content = utils::read_file_safe(&self.path);

        for config in &mut self.configs {
            let mut found = false;
            for line in content.lines() {
                let line = line.trim();
                if line.is_empty() || line.starts_with('#') {
                    continue;
                }

                if let Some((key, value)) = line.split_once('=') {
                    let key = key.trim();
                    let value = value.trim();

                    if key == config.key {
                        found = true;
                        config.current_value = Some(value.to_string());
                        if value == config.value {
                            config.status = ConfigStatus::Exists;
                        } else {
                            config.status = ConfigStatus::Conflict;
                        }
                        break;
                    }
                }
            }

            if !found {
                config.status = ConfigStatus::Missing;
            }
        }

        Ok(())
    }

    fn generate_content(&self) -> String {
        let mut lines = vec![];

        lines.push("# OceanBase sysctl configuration".to_string());
        lines.push("# Generated by yo-ob prepare".to_string());
        lines.push("".to_string());

        for config in &self.configs {
            lines.push(format!("{} = {}", config.key, config.value));
        }

        lines.join("\n") + "\n"
    }

    fn check(&mut self) -> Result<Vec<ConfigItem>> {
        self.parse_existing()?;
        Ok(self.configs.clone())
    }

    fn apply(&mut self, _force: bool) -> Result<()> {
        let content = self.generate_content();
        utils::write_file(&self.path, &content)?;
        Ok(())
    }
}
